name: Run API tests (Newman)

on:
  push:
    branches: [ testing ]
  workflow_dispatch:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman collection with Newman
        
        run: |
          mkdir -p results
          # run collection + environment file saved in repo by two ways
          #1st way by using collection path --->newman run "tests folder name\json file collection name" \
          newman run "API tests/chaining Students collection.postman_collection.json" /
            -e tests/postman/MyEnv.postman_environment.json 
            --env-var "baseUrl=${{ secrets.BASE_URL }}" /
            --reporters cli,junit,json /
            --reporter-junit-export results/junit.xml /
            --reporter-json-export results/results.json /
            #stops the run of tests when a test fails
            --bail

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: newman-reports
          path: results/
